FRC701/valkyrie

vendordeps/REVRobotics.json

Added spark inlcude

---

src/main/cpp/Robot.cpp
src/main/cpp/commands/HatchPuncherDisengage.cpp
src/main/cpp/commands/HatchPuncherEngage.cpp
src/main/cpp/commands/PivotHatch.cpp
src/main/cpp/subsystems/HatchIntake.cpp
src/main/include/RobotMap.h
src/main/include/commands/HatchIntakeDisengage.h
src/main/include/commands/HatchPuncherDisengage.h
src/main/include/commands/HatchPuncherEngage.h
src/main/include/commands/PivotHatch.h
src/main/include/subsystems/HatchIntake.h

Set up talons and pneumatics for RobotMap (IDS are just filler for now)
Set up the basics for a hatch intake subsystem
Added basic commands to test out basic code
Added HatchIntake to Robot

Basic Setup for the HatchIntake Subsystem

---

src/main/cpp/commands/RunCargoRoller.cpp
src/main/cpp/commands/SetCargoDeployerIn.cpp
src/main/cpp/commands/SetCargoDeployerOut.cpp
src/main/cpp/subsystems/CargoIntake.cpp
src/main/include/RobotMap.h
src/main/include/commands/RunCargoRoller.h
src/main/include/commands/SetCargoDeployerIn.h
src/main/include/commands/SetCargoDeployerOut.h
src/main/include/subsystems/CargoIntake.h

rebased from v1 
PTAL
Replaces #8

Feature/cargo intake.v2

---

build.gradle

wpi update

---

src/main/cpp/Robot.cpp
src/main/cpp/commands/CarriageClawDisengage.cpp
src/main/cpp/commands/CarriageClawEngage.cpp
src/main/cpp/commands/CarriagePuncherDisengage.cpp
src/main/cpp/commands/CarriagePuncherEngage.cpp
src/main/cpp/subsystems/CargoCarriage.cpp
src/main/include/RobotMap.h
src/main/include/commands/CarriageClawDisengage.h
src/main/include/commands/CarriageClawEngage.h
src/main/include/commands/CarriagePuncherDisengage.h
src/main/include/commands/CarriagePuncherEngage.h
src/main/include/subsystems/CargoCarriage.h

Feature/cargo carrage.v2

---

src/main/cpp/Robot.cpp
src/main/cpp/commands/ClimberDisengage.cpp
src/main/cpp/commands/ClimberEngage.cpp
src/main/cpp/commands/HatchPuncherDisengage.cpp
src/main/cpp/commands/HatchPuncherEngage.cpp
src/main/cpp/commands/MotorClimb.cpp
src/main/cpp/commands/SetClimber.cpp
src/main/cpp/subsystems/Climber.cpp
src/main/include/RobotMap.h
src/main/include/commands/ClimberDisengage.h
src/main/include/commands/ClimberEngage.h
src/main/include/commands/MotorClimb.h
src/main/include/commands/SetClimber.h
src/main/include/subsystems/Climber.h

Feature/more climber.v1

---

src/main/cpp/OI.cpp
src/main/cpp/Robot.cpp
src/main/cpp/commands/TankDrive.cpp
src/main/cpp/subsystems/Chassis.cpp
src/main/cpp/subsystems/RobotMap.cpp
src/main/include/OI.h
src/main/include/Robot.h
src/main/include/RobotMap.h
src/main/include/commands/TankDrive.h
src/main/include/subsystems/Chassis.h

Chassis: Subsystem and Command

---

src/main/cpp/subsystems/CargoCarriage.cpp
src/main/include/RobotMap.h
src/main/include/subsystems/CargoCarriage.h

Changed IDs and took out left and right claw

---

src/main/cpp/OI.cpp
src/main/cpp/commands/Drive.cpp
src/main/cpp/subsystems/Chassis.cpp
src/main/include/commands/Drive.h
src/main/include/subsystems/Chassis.h

Chassis: Add Drive Command

---

vendordeps/REVRobotics.json

Update the rev driver to 1.0.27

Update rev to 1.0.27

---

src/main/cpp/commands/RunCargoRoller.cpp
src/main/cpp/subsystems/CargoIntake.cpp
src/main/include/commands/RunCargoRoller.h
src/main/include/subsystems/CargoIntake.h

banner sensor for the CargoIntake

---

vendordeps/Phoenix.json

New software needed to make it stop complaining

CTRE Update

---

src/main/cpp/subsystems/Climber.cpp

Changed the pcm number for the Climber Solenoid.

Changed ID for Climber Solenoid

---

src/main/cpp/Robot.cpp
src/main/cpp/subsystems/Chassis.cpp
src/main/include/subsystems/Chassis.h

Chassis Encoder Values (v1)

---

src/main/cpp/utilities/LineCalculator.cpp
src/main/include/utilities/LineCalculator.h

The code has lots of line transfer functions. LineCalculator generalizes the line function.

LineCalculator: Add LineCalculator

---

src/main/cpp/OI.cpp
src/main/cpp/Robot.cpp
src/main/cpp/commands/ResetHatchIntakePosition.cpp
src/main/cpp/commands/SaveHatchIntakeValueFWD.cpp
src/main/cpp/commands/SaveHatchIntakeValueREV.cpp
src/main/cpp/subsystems/HatchIntake.cpp
src/main/include/commands/ResetHatchIntakePosition.h
src/main/include/commands/SaveHatchIntakeValueFWD.h
src/main/include/commands/SaveHatchIntakeValueREV.h
src/main/include/subsystems/HatchIntake.h

Feature/hatch intake calibration.v2

---

src/main/cpp/subsystems/Elevator.cpp

Added SoftLimit

---

src/main/cpp/subsystems/HatchIntake.cpp
src/main/include/subsystems/HatchIntake.h

added soft limits to hatch

---

src/main/cpp/commands/ElevatorDefaultCommand.cpp
src/main/cpp/commands/SetElevator.cpp
src/main/cpp/commands/SetElevatorSpeed.cpp
src/main/cpp/subsystems/Elevator.cpp
src/main/include/commands/ElevatorDefaultCommand.h
src/main/include/commands/SetElevatorSpeed.h
src/main/include/subsystems/Elevator.h

Made Elevator default command

---

src/main/cpp/OI.cpp
src/main/cpp/Robot.cpp
src/main/cpp/commands/HatchIntakeDisengage.cpp
src/main/cpp/commands/HatchIntakeEngage.cpp
src/main/cpp/commands/SetElevatorSpeed.cpp
src/main/cpp/commands/TestingCargoIntake.cpp
src/main/cpp/subsystems/Chassis.cpp
src/main/cpp/subsystems/Elevator.cpp
src/main/include/RobotMap.h
src/main/include/commands/HatchIntakeEngage.h
src/main/include/commands/SetElevatorSpeed.h
src/main/include/commands/TestingCargoIntake.h
src/main/include/subsystems/Elevator.h

Robot Testing

---

src/main/cpp/OI.cpp
src/main/cpp/commands/SetHatchAngle.cpp
src/main/cpp/commands/SetHatchIntakeAngleValue.cpp
src/main/cpp/subsystems/HatchIntake.cpp
src/main/include/commands/SetHatchAngle.h
src/main/include/commands/SetHatchIntakeAngleValue.h
src/main/include/subsystems/HatchIntake.h

Made angle to encoder conversion

---

src/main/cpp/Robot.cpp
src/main/cpp/commands/HatchIntakeDefaultCommand.cpp
src/main/cpp/commands/HatchIntakeToggle.cpp
src/main/cpp/commands/PivotPosition.cpp
src/main/cpp/subsystems/HatchIntake.cpp
src/main/include/commands/HatchIntakeToggle.h
src/main/include/commands/PivotHatch.h
src/main/include/commands/PivotPosition.h
src/main/include/subsystems/HatchIntake.h

Feature/hatch intake.v1

---

src/main/cpp/OI.cpp
src/main/cpp/subsystems/Chassis.cpp
src/main/include/OI.h
src/main/include/RobotMap.h

Added the buttons to OI and added some commands to test. Allowed to chassis to run better and changed the IDs for the pneumatics to match what is on the robot.

Added Buttons, changed RampRate and pneumatic ID's

---

src/main/cpp/OI.cpp
src/main/cpp/Robot.cpp
src/main/cpp/commands/GoToElevatorPosition.cpp
src/main/cpp/commands/ResetElevatorPosition.cpp
src/main/cpp/commands/SetElevatorPositionInches.cpp
src/main/cpp/subsystems/Elevator.cpp
src/main/include/commands/ResetElevatorPosition.h
src/main/include/commands/SetElevatorPositionInches.h
src/main/include/subsystems/Elevator.h

Feature/testing elevator motors.v1

---

src/main/cpp/OI.cpp
src/main/cpp/commands/ElevatorSpeedDefaultCommand.cpp
src/main/cpp/commands/SetElevatorPosDefaultCommand.cpp
src/main/cpp/commands/SetElevatorSpeedDefaultCommand.cpp
src/main/cpp/subsystems/Elevator.cpp
src/main/include/commands/ElevatorSpeedDefaultCommand.h
src/main/include/commands/SetElevatorPosDefaultCommand.h
src/main/include/commands/SetElevatorSpeedDefaultCommand.h
src/main/include/subsystems/Elevator.h

Switch between two default commands for the elevator

Elevator default command

---

src/main/cpp/OI.cpp
src/main/cpp/commands/ElevatorSpeedDefaultCommand.cpp
src/main/cpp/commands/HatchIntakeSpeedDefaultCommand.cpp
src/main/cpp/commands/SetHatchIntakePositionDefaultCommand.cpp
src/main/cpp/commands/SetHatchIntakeSpeedDefaultCommand.cpp
src/main/cpp/subsystems/HatchIntake.cpp
src/main/include/commands/HatchIntakeSpeedDefaultCommand.h
src/main/include/commands/SetHatchIntakePositionDefaultCommand.h
src/main/include/commands/SetHatchIntakeSpeedDefaultCommand.h

Support changing the default commands for the hatch intake.
(FYI -- This uses a slightly different technique than the elevator.)

hatch intake default commands

---

build.gradle

updated WPILib

---

src/main/cpp/OI.cpp
src/main/cpp/Robot.cpp
src/main/cpp/commands/SetHatchIntakePositionDefaultCommand.cpp
src/main/cpp/commands/SetHatchIntakeSpeedDefaultCommand.cpp
src/main/include/Robot.h
src/main/include/commands/SetHatchIntakePositionDefaultCommand.h
src/main/include/commands/SetHatchIntakeSpeedDefaultCommand.h

hatch intake broke build

---

src/main/cpp/OI.cpp
src/main/cpp/Robot.cpp
src/main/cpp/commands/ElevatorSpeedDefaultCommand.cpp
src/main/cpp/commands/FullArmPosition.cpp
src/main/cpp/commands/PivotPositionByAngle.cpp
src/main/cpp/commands/RunCargoRoller.cpp
src/main/cpp/commands/dLBPressed.cpp
src/main/cpp/commands/dLBReleased.cpp
src/main/cpp/subsystems/Chassis.cpp
src/main/cpp/subsystems/Elevator.cpp
src/main/cpp/subsystems/HatchIntake.cpp
src/main/include/OI.h
src/main/include/commands/PivotPositionByAngle.h
src/main/include/commands/dLBPressed.h
src/main/include/commands/dLBReleased.h
src/main/include/subsystems/Chassis.h
src/main/include/subsystems/Elevator.h
src/main/include/subsystems/HatchIntake.h

Feature/more armijo changes.v4

---

src/main/include/utilities/LineCalculator.h

Support returning the invert of the line as another line calculator.
Closes #73

Line Calculator: Add invert

---

src/main/cpp/subsystems/Climber.cpp
src/main/include/subsystems/Climber.h

The climber motor is now a spark.

Climber: Use spark for climber

---

build.gradle

WPILib Update

---

src/main/cpp/OI.cpp
src/main/cpp/commands/VisionDrive.cpp
src/main/cpp/subsystems/Chassis.cpp
src/main/include/commands/VisionDrive.h
src/main/include/subsystems/Chassis.h

Made vision drive

---

src/main/cpp/OI.cpp
src/main/cpp/commands/FullArmPosition.cpp
src/main/cpp/commands/FullElevatorLevel.cpp
src/main/cpp/commands/OpenCargoSqueeze.cpp
src/main/cpp/commands/SetCargoSqueeze.cpp
src/main/cpp/subsystems/CargoIntake.cpp
src/main/include/commands/OpenCargoSqueeze.h
src/main/include/commands/SetCargoSqueeze.h
src/main/include/subsystems/CargoIntake.h

Changing Deployer to Squeezer

---

src/main/cpp/OI.cpp
src/main/cpp/commands/SetCamModeDriver.cpp
src/main/cpp/commands/SetCamModeVision.cpp
src/main/cpp/commands/SetControlDrive.cpp
src/main/cpp/commands/SetVisionDrive.cpp
src/main/cpp/subsystems/Chassis.cpp
src/main/include/commands/SetCamModeDriver.h
src/main/include/commands/SetCamModeVision.h
src/main/include/commands/SetControlDrive.h
src/main/include/commands/SetVisionDrive.h
src/main/include/subsystems/Chassis.h

Added camera modes and organized variables

---

src/main/cpp/OI.cpp
src/main/cpp/commands/HatchCargoSelector.cpp
src/main/include/OI.h
src/main/include/commands/HatchCargoSelector.h

Chooser for Hatch and Cargo

---

src/main/cpp/Robot.cpp
src/main/cpp/subsystems/HatchIntake.cpp
src/main/include/subsystems/HatchIntake.h

This might fix a bug where the hatch intake position initializes differently on each reboot.

hatch intake does not init

---

src/main/cpp/commands/SetClimbMotorSpeed.cpp
src/main/cpp/subsystems/Climber.cpp
src/main/include/subsystems/Climber.h

implemented a reset encoder for climber

---

src/main/cpp/subsystems/HatchIntake.cpp
src/main/include/subsystems/HatchIntake.h
src/main/include/utilities/Preference.h

Simple Preference Object

---

src/main/cpp/OI.cpp
src/main/cpp/Robot.cpp
src/main/cpp/commands/HatchIntakeDefaultCommand.cpp
src/main/cpp/subsystems/Elevator.cpp
src/main/cpp/subsystems/HatchIntake.cpp
src/main/include/subsystems/Elevator.h
src/main/include/subsystems/HatchIntake.h
src/main/include/utilities/Preference.h

PTAL
Fixes #113 
Fixes #112 
Fixes #110

Feature/increasing arm speed.v1

---

src/main/cpp/commands/CargoRoller.cpp
src/main/cpp/commands/FullCargoIntake.cpp
src/main/include/commands/CargoRoller.h

added cargo hold to cargo roller

---

src/main/cpp/OI.cpp
src/main/cpp/commands/VisionDrive.cpp
src/main/cpp/subsystems/Chassis.cpp
src/main/include/subsystems/Chassis.h

I finally got to test vision!! - it works
replaces #127

vision tuning angle and depth
